POST http://localhost:3000/registro
Content-Type: application/json

{
  "nombre": "Maria",
  "mensaje": "Hola comunidad"
}

### Otra incidencia POST
POST http://localhost:3000/incidencia
Content-Type: application/json

{
  "tipo": "Recolección Basura",
  "descripcion": "La comunidad reporta que no se recoje la basura hace varios días."
}

